version: "3.3"
services:
  app:
    build:
      context: ../
      dockerfile: ./.hub/Dockerfile
    restart: always
    volumes:
      - ..:/usr/src/app
      - ../node_modules:/usr/src/app/node_modules/
    command: npm run start
